// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.architecture.properties.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.architecture.serialization.api.*
import com.github.bratek20.architecture.serialization.fixtures.*

import com.github.bratek20.architecture.properties.api.*

fun assertSerializedProperty(given: SerializedProperty, expectedInit: ExpectedSerializedProperty.() -> Unit) {
    val diff = diffSerializedProperty(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}