// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.architecture.properties.fixtures

import com.github.bratek20.architecture.serialization.api.*
import com.github.bratek20.architecture.serialization.fixtures.*

import com.github.bratek20.architecture.properties.api.*

data class SerializedPropertyDef(
    var keyName: String = "someValue",
    var value: (SerializedValueDef.() -> Unit) = {},
)
fun serializedProperty(init: SerializedPropertyDef.() -> Unit = {}): SerializedProperty {
    val def = SerializedPropertyDef().apply(init)
    return SerializedProperty.create(
        keyName = def.keyName,
        value = serializedValue(def.value),
    )
}