// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.httpclient.api

import com.github.bratek20.architecture.exceptions.ApiException

class HttpClientException(
    message: String = ""
): ApiException(message) {
}

class HttpRequesterException(
    message: String = ""
): ApiException(message) {
}