// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.httpclient.api

interface HttpClient {
    fun get(path: String): HttpResponse

    fun post(path: String, body: Any?): HttpResponse
}

interface HttpClientFactory {
    fun create(config: HttpClientConfig): HttpClient
}