// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.httpclient.api

interface HttpClient {
    fun get(url: String): String
}

interface HttpClientFactory {
    fun create(): HttpClient
}