// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.httpclient.api

interface HttpClient {
    @Throws(
        HttpClientException::class,
    )
    fun post(path: String, body: Any?): HttpResponse
}

interface HttpClientFactory {
    fun create(config: HttpClientConfig): HttpClient
}

interface HttpRequester {
    @Throws(
        HttpRequesterException::class,
    )
    fun send(request: HttpRequest): SendResponse
}