// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.httpclient.api

data class HttpClientAuth(
    private val username: String,
    private val password: String,
) {
    fun getUsername(): String {
        return this.username
    }

    fun getPassword(): String {
        return this.password
    }

    companion object {
        fun create(
            username: String,
            password: String,
        ): HttpClientAuth {
            return HttpClientAuth(
                username = username,
                password = password,
            )
        }
    }
}

data class FactoryCreateArgs(
    private val baseUrl: String,
    private val auth: HttpClientAuth? = null,
) {
    fun getBaseUrl(): String {
        return this.baseUrl
    }

    fun getAuth(): HttpClientAuth? {
        return this.auth
    }

    companion object {
        fun create(
            baseUrl: String,
            auth: HttpClientAuth? = null,
        ): FactoryCreateArgs {
            return FactoryCreateArgs(
                baseUrl = baseUrl,
                auth = auth,
            )
        }
    }
}