// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthclient.api

import com.github.bratek20.infrastructure.userauthserver.api.*

val USER_MAPPING_DATA_KEY = com.github.bratek20.architecture.data.api.ObjectDataKey(
    "UserMapping",
    UserMapping::class
)