// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthclient.api

import com.github.bratek20.architecture.exceptions.ApiException
import com.github.bratek20.infrastructure.userauthserver.api.*

class NotLoggedInException(
    message: String = ""
): ApiException(message) {
}