// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthclient.api

import com.github.bratek20.infrastructure.userauthserver.api.*

interface UserAuthClientApi {
    fun login(): Unit

    @Throws(
        NotLoggedInException::class,
    )
    fun getUserId(): UserId
}