ExternalTypes
    Struct
    StructList

ValueObjects
    //[*] means all elements of list
    //[n] means n-th element of list
    StructPath: string (example: "field/[*]/a/b/[0]/c")

    //for now always string
    StructPrimitive: string

Interfaces
    AnyStruct
        isObject(): bool
        isList(): bool
        isPrimitive(): bool

        asObject(): Struct
            throws
                StructConversionException

        asList(): StructList
            throws
                StructConversionException

        asPrimitive(): StructPrimitive
            throws
                StructConversionException


    AnyStructHelper
        getValues(struct: AnyStruct, path: StructPath): AnyStruct[]
            throws
                WrongStructPathException