ExternalTypes
    Struct
    StructList
    StructPrimitive

ValueObjects
    //[*] means all elements of list
    //[n] means n-th element of list
    //ending field name with ? means field can be null
    StructPath: string (example: "field/[*]/a/b?/[0]/c")

Interfaces
    AnyStruct
        isObject(): bool
        isList(): bool
        isPrimitive(): bool

        asObject(): Struct
            throws
                StructConversionException

        asList(): StructList
            throws
                StructConversionException

        asPrimitive(): StructPrimitive
            throws
                StructConversionException


    AnyStructHelper
        getValues(struct: AnyStruct, path: StructPath): AnyStruct[]
            throws
                StructTraversalException