// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.architecture.structs.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.architecture.structs.api.*

fun assertStructPath(given: StructPath, expected: String) {
    val diff = diffStructPath(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}


fun assertStructValue(given: StructValue, expected: String) {
    val diff = diffStructValue(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertStruct(given: Struct, expectedInit: ExpectedStruct.() -> Unit) {
    val diff = diffStruct(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertStructList(given: StructList, expectedInit: ExpectedStructList.() -> Unit) {
    val diff = diffStructList(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}