// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.architecture.structs.fixtures

import com.github.bratek20.architecture.structs.api.*

fun structPath(value: String = "field/[*]/a/b/[0]/c"): StructPath {
    return StructPath(value)
}

fun structValue(value: String = "someValue"): StructValue {
    return StructValue(value)
}

data class StructDef(
)
fun struct(init: StructDef.() -> Unit = {}): Struct {
    val def = StructDef().apply(init)
    return structCreate(
    )
}

data class StructListDef(
)
fun structList(init: StructListDef.() -> Unit = {}): StructList {
    val def = StructListDef().apply(init)
    return structListCreate(
    )
}