// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.architecture.structs.fixtures

import com.github.bratek20.architecture.structs.api.*

fun structPath(value: String = "field/[*]/a/b/[0]/c"): StructPath {
    return StructPath(value)
}

fun structValue(value: String = "someValue"): StructValue {
    return StructValue(value)
}