// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.architecture.serialization.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.architecture.serialization.api.*

fun assertSerializedValue(given: SerializedValue, expectedInit: ExpectedSerializedValue.() -> Unit) {
    val diff = diffSerializedValue(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}