// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.architecture.serialization.fixtures

import com.github.bratek20.architecture.serialization.api.*

data class SerializedValueDef(
    var value: String = "someValue",
    var type: SerializationType = SerializationType.JSON,
)
fun serializedValue(init: SerializedValueDef.() -> Unit = {}): SerializedValue {
    val def = SerializedValueDef().apply(init)
    return SerializedValue.create(
        value = def.value,
        type = def.type,
    )
}