// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.httpclient.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.infrastructure.httpclient.api.*

fun assertHttpClientAuth(given: HttpClientAuth, expectedInit: ExpectedHttpClientAuth.() -> Unit) {
    val diff = diffHttpClientAuth(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertHttpClientConfig(given: HttpClientConfig, expectedInit: ExpectedHttpClientConfig.() -> Unit) {
    val diff = diffHttpClientConfig(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertHttpHeader(given: HttpHeader, expectedInit: ExpectedHttpHeader.() -> Unit) {
    val diff = diffHttpHeader(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertHttpRequest(given: HttpRequest, expectedInit: ExpectedHttpRequest.() -> Unit) {
    val diff = diffHttpRequest(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertSendResponse(given: SendResponse, expectedInit: ExpectedSendResponse.() -> Unit) {
    val diff = diffSendResponse(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}