// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.httpclient.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.infrastructure.httpclient.api.*

fun assertHttpClientAuth(given: HttpClientAuth, expectedInit: ExpectedHttpClientAuth.() -> Unit) {
    val diff = diffHttpClientAuth(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertHttpClientConfig(given: HttpClientConfig, expectedInit: ExpectedHttpClientConfig.() -> Unit) {
    val diff = diffHttpClientConfig(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}