// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.httpclient.fixtures

import com.github.bratek20.infrastructure.httpclient.api.*

data class HttpClientAuthDef(
    var username: String = "someValue",
    var password: String = "someValue",
)
fun httpClientAuth(init: HttpClientAuthDef.() -> Unit = {}): HttpClientAuth {
    val def = HttpClientAuthDef().apply(init)
    return HttpClientAuth.create(
        username = def.username,
        password = def.password,
    )
}

data class HttpClientConfigDef(
    var baseUrl: String = "someValue",
    var auth: (HttpClientAuthDef.() -> Unit)? = null,
)
fun httpClientConfig(init: HttpClientConfigDef.() -> Unit = {}): HttpClientConfig {
    val def = HttpClientConfigDef().apply(init)
    return HttpClientConfig.create(
        baseUrl = def.baseUrl,
        auth = def.auth?.let { it -> httpClientAuth(it) },
    )
}