// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.httpclient.fixtures

import com.github.bratek20.infrastructure.httpclient.api.*

data class HttpClientAuthDef(
    var username: String = "someValue",
    var password: String = "someValue",
)
fun httpClientAuth(init: HttpClientAuthDef.() -> Unit = {}): HttpClientAuth {
    val def = HttpClientAuthDef().apply(init)
    return HttpClientAuth.create(
        username = def.username,
        password = def.password,
    )
}

data class FactoryCreateArgsDef(
    var baseUrl: String = "someValue",
    var auth: (HttpClientAuthDef.() -> Unit)? = null,
)
fun factoryCreateArgs(init: FactoryCreateArgsDef.() -> Unit = {}): FactoryCreateArgs {
    val def = FactoryCreateArgsDef().apply(init)
    return FactoryCreateArgs.create(
        baseUrl = def.baseUrl,
        auth = def.auth?.let { it -> httpClientAuth(it) },
    )
}