// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.utils.directory.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.utils.directory.api.*

fun assertFileName(given: FileName, expected: String) {
    val diff = diffFileName(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}


fun assertDirectoryName(given: DirectoryName, expected: String) {
    val diff = diffDirectoryName(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}


fun assertPath(given: Path, expected: String) {
    val diff = diffPath(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}


fun assertFileContent(given: FileContent, expected: String) {
    val diff = diffFileContent(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertFile(given: File, expectedInit: ExpectedFile.() -> Unit) {
    val diff = diffFile(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertDirectory(given: Directory, expectedInit: ExpectedDirectory.() -> Unit) {
    val diff = diffDirectory(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}

fun assertCompareResult(given: CompareResult, expectedInit: ExpectedCompareResult.() -> Unit) {
    val diff = diffCompareResult(given, expectedInit)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}