// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.utils.directory.api

import com.github.bratek20.architecture.exceptions.ApiException

class FileNotFoundException(message: String = "") : ApiException(message)

class DirectoryNotFoundException(message: String = "") : ApiException(message)