// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.architecture.serialization.api

data class SerializedValue(
    private val value: String,
    private val type: String,
) {
    fun getValue(): String {
        return this.value
    }

    fun getType(): SerializationType {
        return SerializationType.valueOf(this.type)
    }

    companion object {
        fun create(
            value: String,
            type: SerializationType,
        ): SerializedValue {
            return SerializedValue(
                value = value,
                type = type.name,
            )
        }
    }
}

data class SerializerConfig(
    private val readable: Boolean = false,
) {
    fun getReadable(): Boolean {
        return this.readable
    }

    companion object {
        fun create(
            readable: Boolean = false,
        ): SerializerConfig {
            return SerializerConfig(
                readable = readable,
            )
        }
    }
}