// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.architecture.users.fixtures

import org.assertj.core.api.Assertions.assertThat

import com.github.bratek20.architecture.users.api.*

fun assertUserId(given: UserId, expected: Int) {
    val diff = diffUserId(given, expected)
    assertThat(diff).withFailMessage(diff).isEqualTo("")
}
