// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.architecture.users.fixtures

import com.github.bratek20.architecture.users.api.*

fun userId(value: Int = 0): UserId {
    return UserId(value)
}
