// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.architecture.users.fixtures

import com.github.bratek20.architecture.users.api.*

fun diffUserId(given: UserId, expected: Int, path: String = ""): String {
    if (given.value != expected) { return "${path}value ${given.value} != ${expected}" }
    return ""
}
