// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.architecture.properties.api

import com.github.bratek20.architecture.serialization.api.*

data class SerializedProperty(
    private val keyName: String,
    private val value: SerializedValue,
) {
    fun getKeyName(): String {
        return this.keyName
    }

    fun getValue(): SerializedValue {
        return this.value
    }

    companion object {
        fun create(
            keyName: String,
            value: SerializedValue,
        ): SerializedProperty {
            return SerializedProperty(
                keyName = keyName,
                value = value,
            )
        }
    }
}