// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthserver.web

import com.github.bratek20.architecture.users.api.UserId
import com.github.bratek20.infrastructure.httpclient.api.HttpClientConfig

import com.github.bratek20.infrastructure.userauthserver.api.*

class UserAuthServerWebClientConfig(
    val value: HttpClientConfig
) {
}
class UserAuthServerApiCreateUserAndLoginResponse(
    private val value: UserMapping
) {
    fun getValue(): UserMapping {
        return value
    }
}
class UserAuthServerApiLoginRequest(
    private val authId: String
) {
    fun getAuthId(): AuthId {
        return AuthId(authId)
    }
    companion object {
        fun create(authId: AuthId): UserAuthServerApiLoginRequest {
            return UserAuthServerApiLoginRequest(authId.value)
        }
    }
}
class UserAuthServerApiLoginResponse(
    private val value: Int
) {
    fun getValue(): UserId {
        return UserId(value)
    }
}