// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthserver.web

import com.github.bratek20.infrastructure.httpclient.api.HttpClientFactory

import com.github.bratek20.infrastructure.userauthserver.api.*

import com.github.bratek20.architecture.users.api.*

class UserAuthServerApiWebClient(
    factory: HttpClientFactory,
    config: UserAuthServerWebClientConfig,
): UserAuthServerApi {
    private val client = factory.create(config.value)

    override fun createUserAndLogin(): UserMapping {
        return client.post("/b20/userAuthServerApi/createUserAndLogin", null).getBody(UserAuthServerApiCreateUserAndLoginResponse::class.java).getValue()
    }

    override fun login(authId: AuthId): UserMapping {
        return client.post("/b20/userAuthServerApi/login", UserAuthServerApiLoginRequest.create(authId)).getBody(UserAuthServerApiLoginResponse::class.java).getValue()
    }
}

