// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthserver.web

import com.github.bratek20.architecture.context.api.ContextBuilder
import com.github.bratek20.infrastructure.httpserver.api.WebServerModule

import com.github.bratek20.infrastructure.userauthserver.impl.UserAuthServerImpl

class UserAuthServerWebServer: WebServerModule {
    override fun apply(builder: ContextBuilder) {
        builder.withModule(UserAuthServerImpl())
    }

    override fun getControllers(): List<Class<*>> {
        return listOf(
            UserAuthServerApiController::class.java,
        )
    }
}