Enums
    HttpMethod
        GET
        POST

ExternalTypes
    HttpResponse // TODO-REF hla missing generic types support
        //getStatusCode(): Int
        //getBody<T>(type: Class<T>): T

ValueObjects
    HttpClientAuth
        username: string
        password: string
    HttpClientConfig
       baseUrl: string
       auth: HttpClientAuth? = empty
       persistSession: bool = false

Interfaces
    HttpClient
        get(path: String): HttpResponse
        post(path: String, body: any?): HttpResponse

    HttpClientFactory
        create(config: HttpClientConfig): HttpClient

    //incoming
    HttpRequester
        HttpHeader
            key: string
            value: string
        HttpRequest
            url: string
            method: HttpMethod
            content: string?
            contentType: string
            headers: HttpHeader[]
        SendResponse
            statusCode: int
            body: string
        send(request: HttpRequest): SendResponse
            throws
                HttpRequesterException