ValueObjects
    AuthId: string

Data
    UserMapping
        authId: AuthId
        userId: UserId
    "UsersMapping" -> UserMapping[]

Exceptions
    NotLoggedInException

Interfaces
    UserAuthServerApi
        createUserAndLogin(): UserMapping
    
        login(authId: AuthId): UserId
            throws
                UserMappingNotFoundException

    AuthIdGenerator
        generate(): AuthId

//Commented as some custom code was added to generated code
//Web
    //Http
        //ExposedInterfaces
            //UserAuthServerApi
        //urlPathPrefix = "/b20"

Fixtures
    MockedInterfaces
        UserAuthServerApi