// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthserver.fixtures

import com.github.bratek20.infrastructure.userauthserver.api.*

fun authId(value: String = "someValue"): AuthId {
    return AuthId(value)
}

fun userId(value: String = "someValue"): UserId {
    return UserId(value)
}

data class UserMappingDef(
    var authId: String = "someValue",
    var userId: String = "someValue",
)
fun userMapping(init: UserMappingDef.() -> Unit = {}): UserMapping {
    val def = UserMappingDef().apply(init)
    return UserMapping.create(
        authId = AuthId(def.authId),
        userId = UserId(def.userId),
    )
}