// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthserver.fixtures

import com.github.bratek20.architecture.users.api.*
import com.github.bratek20.architecture.users.fixtures.*

import com.github.bratek20.infrastructure.userauthserver.api.*

fun authId(value: String = "someValue"): AuthId {
    return AuthId(value)
}

data class UserAuthServerPropertiesDef(
    var createNewUserForUnknownAuthId: Boolean = false,
)
fun userAuthServerProperties(init: UserAuthServerPropertiesDef.() -> Unit = {}): UserAuthServerProperties {
    val def = UserAuthServerPropertiesDef().apply(init)
    return UserAuthServerProperties.create(
        createNewUserForUnknownAuthId = def.createNewUserForUnknownAuthId,
    )
}

data class UserMappingDef(
    var authId: String = "someValue",
    var userId: Int = 0,
)
fun userMapping(init: UserMappingDef.() -> Unit = {}): UserMapping {
    val def = UserMappingDef().apply(init)
    return UserMapping.create(
        authId = AuthId(def.authId),
        userId = UserId(def.userId),
    )
}