// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthserver.fixtures

import com.github.bratek20.architecture.users.api.*
import com.github.bratek20.architecture.users.fixtures.*

import com.github.bratek20.infrastructure.userauthserver.api.*

fun diffAuthId(given: AuthId, expected: String, path: String = ""): String {
    if (given.value != expected) { return "${path}value ${given.value} != ${expected}" }
    return ""
}

data class ExpectedUserAuthServerProperties(
    var createNewUserForUnknownAuthId: Boolean? = null,
)
fun diffUserAuthServerProperties(given: UserAuthServerProperties, expectedInit: ExpectedUserAuthServerProperties.() -> Unit, path: String = ""): String {
    val expected = ExpectedUserAuthServerProperties().apply(expectedInit)
    val result: MutableList<String> = mutableListOf()

    expected.createNewUserForUnknownAuthId?.let {
        if (given.getCreateNewUserForUnknownAuthId() != it) { result.add("${path}createNewUserForUnknownAuthId ${given.getCreateNewUserForUnknownAuthId()} != ${it}") }
    }

    return result.joinToString("\n")
}

data class ExpectedUserMapping(
    var authId: String? = null,
    var userId: Int? = null,
)
fun diffUserMapping(given: UserMapping, expectedInit: ExpectedUserMapping.() -> Unit, path: String = ""): String {
    val expected = ExpectedUserMapping().apply(expectedInit)
    val result: MutableList<String> = mutableListOf()

    expected.authId?.let {
        if (diffAuthId(given.getAuthId(), it) != "") { result.add(diffAuthId(given.getAuthId(), it, "${path}authId.")) }
    }

    expected.userId?.let {
        if (diffUserId(given.getUserId(), it) != "") { result.add(diffUserId(given.getUserId(), it, "${path}userId.")) }
    }

    return result.joinToString("\n")
}