// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.architecture.structs.api

import com.github.bratek20.architecture.exceptions.ApiException

class StructConversionException(
    message: String = ""
): ApiException(message) {
}

class WrongStructPathException(
    message: String = ""
): ApiException(message) {
}