// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.architecture.structs.api

interface AnyStruct {
    fun isObject(): Boolean

    fun isList(): Boolean

    fun isPrimitive(): Boolean

    @Throws(
        StructConversionException::class,
    )
    fun asObject(): com.github.bratek20.architecture.structs.api.Struct

    @Throws(
        StructConversionException::class,
    )
    fun asList(): StructList

    @Throws(
        StructConversionException::class,
    )
    fun asPrimitive(): StructPrimitive
}

interface AnyStructHelper {
    @Throws(
        StructTraversalException::class,
    )
    fun getValues(struct: AnyStruct, path: StructPath): List<AnyStruct>
}