// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.architecture.structs.api

data class StructPath(
    val value: String
) {
    override fun toString(): String {
        return value.toString()
    }
}

data class StructPrimitive(
    val value: String
) {
    override fun toString(): String {
        return value.toString()
    }
}