// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthserver.api

data class UserMapping(
    private var authId: String,
    private var userId: String,
) {
    fun getAuthId(): AuthId {
        return AuthId(this.authId)
    }

    fun getUserId(): UserId {
        return UserId(this.userId)
    }

    fun setAuthId(authId: AuthId) {
        this.authId = authId.value
    }

    fun setUserId(userId: UserId) {
        this.userId = userId.value
    }

    companion object {
        fun create(
            authId: AuthId,
            userId: UserId,
        ): UserMapping {
            return UserMapping(
                authId = authId.value,
                userId = userId.value,
            )
        }
    }

    fun update(other: UserMapping) {
        this.authId = other.authId
        this.userId = other.userId
    }
}