// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthserver.api

val USERS_MAPPING_DATA_KEY = com.github.bratek20.architecture.data.api.ListDataKey(
    "UsersMapping",
    UserMapping::class
)