// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthserver.api

import com.github.bratek20.architecture.exceptions.ApiException
import com.github.bratek20.architecture.users.api.*

class UserMappingNotFoundException(
    message: String = ""
): ApiException(message) {
}

class NotLoggedInException(
    message: String = ""
): ApiException(message) {
}