// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthserver.api

import com.github.bratek20.architecture.users.api.*

interface UserAuthServerApi {
    fun createUserAndLogin(): UserMapping

    @Throws(
        UnknownAuthIdException::class,
    )
    fun login(authId: AuthId): UserMapping
}

interface AuthIdGenerator {
    fun generate(): AuthId
}