// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthserver.api

interface UserAuthServerApi {
    fun createUserAndLogin(): UserMapping

    @Throws(
        UserMappingNotFoundException::class,
    )
    fun login(authId: AuthId): UserId
}

interface UserSession {
    @Throws(
        NotLoggedInException::class,
    )
    fun getUserId(): UserId
}