// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthserver.api

import com.github.bratek20.architecture.users.api.*

val USER_AUTH_SERVER_CONFIG_PROPERTY_KEY = com.github.bratek20.architecture.properties.api.ObjectPropertyKey(
    "UserAuthServerConfig",
    UserAuthServerConfig::class
)