// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthserver.api

import com.github.bratek20.architecture.users.api.*

data class AuthId(
    val value: String
) {
    override fun toString(): String {
        return value.toString()
    }
}

data class UserAuthServerProperties(
    private val createNewUserForUnknownAuthId: Boolean = false,
) {
    fun getCreateNewUserForUnknownAuthId(): Boolean {
        return this.createNewUserForUnknownAuthId
    }

    companion object {
        fun create(
            createNewUserForUnknownAuthId: Boolean = false,
        ): UserAuthServerProperties {
            return UserAuthServerProperties(
                createNewUserForUnknownAuthId = createNewUserForUnknownAuthId,
            )
        }
    }
}