// DO NOT EDIT! Autogenerated by HLA tool

package com.github.bratek20.infrastructure.userauthserver.api

data class AuthId(
    val value: String
) {
    override fun toString(): String {
        return value.toString()
    }
}

data class UserId(
    val value: String
) {
    override fun toString(): String {
        return value.toString()
    }
}